# Generated by Django 4.1.5 on 2023-01-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dinero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(max_length=100)),
                ('cuanto', models.FloatField()),
                ('existe', models.BooleanField()),
            ],
        ),
    ]
