# Generated by Django 4.1.5 on 2023-01-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinero', '0003_banco_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dinero',
            options={'verbose_name': 'Dinero', 'verbose_name_plural': 'Movimientos con dinero'},
        ),
    ]
