# Generated by Django 4.1.5 on 2023-02-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinero', '0004_alter_dinero_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinero',
            name='nombre_banco',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
