# Generated by Django 4.1.5 on 2023-01-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_del_titular', models.CharField(max_length=35)),
                ('Banco', models.CharField(choices=[('CITI', 'CITI'), ('SANTANDER', 'SANTANDER'), ('BBVA', 'BBVA')], max_length=30)),
                ('Numero_de_cuenta', models.FloatField()),
                ('Codigo_Postal', models.FloatField()),
            ],
        ),
    ]
