# Generated by Django 4.1.5 on 2023-01-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='Numero_de_cuenta',
            field=models.BigIntegerField(),
        ),
    ]
