# Generated by Django 4.1.5 on 2023-01-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_alter_cuenta_numero_de_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
