# Generated by Django 4.1.5 on 2023-01-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_cuenta_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='Codigo_Postal',
            field=models.BigIntegerField(),
        ),
    ]
